# Generated by Django 5.2.4 on 2025-08-26 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='photo_url',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
