# Generated by Django 5.2.4 on 2025-10-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_category_options_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceimage',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'service')},
        ),
    ]
