# Generated by Django 5.2.4 on 2025-10-10 05:13

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_category_options_order_total_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['id'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('ASSEMBLY', 'Assembly'), ('DISASSEMBLY', 'Disassembly'), ('BOTH', 'Both'), ('MOUNTING', 'Mounting'), ('DISMOUNTING', 'Dismounting'), ('INSTALLATION', 'Installation')], default='ASSEMBLY', max_length=20)),
                ('need_moving', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=3)),
                ('how_far', models.CharField(blank=True, choices=[('LT10', 'Less than 10 FT'), ('GT10', 'More than 10 FT')], max_length=10, null=True)),
                ('moving_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('related_image', models.ImageField(blank=True, null=True, upload_to='service_photos/related_photos/')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='app.service')),
            ],
            options={
                'verbose_name': 'Service type',
                'verbose_name_plural': 'service types',
                'ordering': ['service_type'],
            },
        ),
    ]
