# Generated by Django 5.2.4 on 2025-10-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_service_options_servicetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetype',
            name='service',
        ),
        migrations.AddField(
            model_name='servicetype',
            name='service',
            field=models.ManyToManyField(related_name='service_types', to='app.service'),
        ),
    ]
